### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by gkowalski**
- Added Spacy NLP Library to perform basic PERSON Identification
- Dockerfile added for basic startup
- Cleaned up code per PEP8

### CODE REVIEW

**Comment by tschaffter** [comment]
> Fixed the Horrible NO newline at end of file !

George 1 Bot 0!

**Comment by tschaffter** [comment]
@gkowalski Is this PR ready for review? I forget whether you have permission to assign reviewer(s).

**Comment by gkowalski** [comment]
Yes it is . I cannot assign anyone to a PR from my repository.

**Comment by tschaffter** [comment]
@gkowalski As a reminder, branches that you use for PR should be discarded. Now because you have use the branch `develop` of your fork, you may want to hard reset it. In the future, it's preferable to do work in feature branch.

**Pull request merged**
